POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blog List",
  "author": "Oblomov",
  "url": "http://localhost:3003",
  "likes": 4
}

###

GET http://localhost:3003/api/blogs